/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LOSETTINGS_PB_H_INCLUDED
#define PB_LOSETTINGS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(257) LoSettingsKv_data_t;
/* Tagged KV value. `kind` is the type code; `data` holds the raw payload bytes.
 1=bool 2=int32 3=uint32 4=float 5=string 6=bytes */
typedef struct _LoSettingsKv {
    char key[33];
    uint32_t kind;
    LoSettingsKv_data_t data;
} LoSettingsKv;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define LoSettingsKv_init_default                {"", 0, {0, {0}}}
#define LoSettingsKv_init_zero                   {"", 0, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define LoSettingsKv_key_tag                     1
#define LoSettingsKv_kind_tag                    2
#define LoSettingsKv_data_tag                    3

/* Struct field encoding specification for nanopb */
#define LoSettingsKv_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   key,               1) \
X(a, STATIC,   SINGULAR, UINT32,   kind,              2) \
X(a, STATIC,   SINGULAR, BYTES,    data,              3)
#define LoSettingsKv_CALLBACK NULL
#define LoSettingsKv_DEFAULT NULL

extern const pb_msgdesc_t LoSettingsKv_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define LoSettingsKv_fields &LoSettingsKv_msg

/* Maximum encoded size of messages (where known) */
#define LOSETTINGS_PB_H_MAX_SIZE                 LoSettingsKv_size
#define LoSettingsKv_size                        300

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
