/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LOFI_PB_H_INCLUDED
#define PB_LOFI_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _KnownWifi {
    char ssid[33];
    char psk[65];
    bool favorite;
    uint32_t last_connected;
    uint32_t connect_count;
} KnownWifi;

typedef struct _ScanSeen {
    char ssid[33];
    pb_byte_t bssid[6];
    int32_t rssi;
    uint32_t last_seen;
    uint32_t channel;
    uint32_t auth;
} ScanSeen;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define KnownWifi_init_default                   {"", "", 0, 0, 0}
#define ScanSeen_init_default                    {"", {0}, 0, 0, 0, 0}
#define KnownWifi_init_zero                      {"", "", 0, 0, 0}
#define ScanSeen_init_zero                       {"", {0}, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define KnownWifi_ssid_tag                       1
#define KnownWifi_psk_tag                        2
#define KnownWifi_favorite_tag                   3
#define KnownWifi_last_connected_tag             4
#define KnownWifi_connect_count_tag              5
#define ScanSeen_ssid_tag                        1
#define ScanSeen_bssid_tag                       2
#define ScanSeen_rssi_tag                        3
#define ScanSeen_last_seen_tag                   4
#define ScanSeen_channel_tag                     5
#define ScanSeen_auth_tag                        6

/* Struct field encoding specification for nanopb */
#define KnownWifi_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   ssid,              1) \
X(a, STATIC,   SINGULAR, STRING,   psk,               2) \
X(a, STATIC,   SINGULAR, BOOL,     favorite,          3) \
X(a, STATIC,   SINGULAR, UINT32,   last_connected,    4) \
X(a, STATIC,   SINGULAR, UINT32,   connect_count,     5)
#define KnownWifi_CALLBACK NULL
#define KnownWifi_DEFAULT NULL

#define ScanSeen_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   ssid,              1) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, bssid,             2) \
X(a, STATIC,   SINGULAR, INT32,    rssi,              3) \
X(a, STATIC,   SINGULAR, UINT32,   last_seen,         4) \
X(a, STATIC,   SINGULAR, UINT32,   channel,           5) \
X(a, STATIC,   SINGULAR, UINT32,   auth,              6)
#define ScanSeen_CALLBACK NULL
#define ScanSeen_DEFAULT NULL

extern const pb_msgdesc_t KnownWifi_msg;
extern const pb_msgdesc_t ScanSeen_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define KnownWifi_fields &KnownWifi_msg
#define ScanSeen_fields &ScanSeen_msg

/* Maximum encoded size of messages (where known) */
#define KnownWifi_size                           114
#define LOFI_PB_H_MAX_SIZE                       KnownWifi_size
#define ScanSeen_size                            71

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
